//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---
using AmitalCloud.Infrastructure.Model.BaseClasses;
using AmitalCloud.Infrastructure.Model.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace AmitalCloud.Infrastructure.Model.EntityClasses
{
	[DataBase(AmitalCloudDBSchema.AMITAL_MAIN)]
	[Table("MenuButtons")]
    public class MenuButton : BaseEntity
	{
		
           [ForeignKey("MenuButtonGroup")]
        [Column("MenuButtonGroupId")]
	    public string MenuButtonGroupId { get; set; }
	      
        public virtual MenuButtonGroup MenuButtonGroup { get; set; }
     [Key]
        [Column("Id")]
	    public string Id { get; set; }
        [Column("Tenant")]
	    public int Tenant { get; set; }
        [Column("LabelTextCodeId")]
	    public string LabelTextCodeId { get; set; }
        [Column("ParentMenuButtonId")]
	    public string ParentMenuButtonId { get; set; }
        [Column("EventCode")]
	    public string EventCode { get; set; }
        [Column("Index")]
	    public int Index { get; set; }
        [Column("IsActive")]
	    public bool IsActive { get; set; }
        [ForeignKey("Feature")]
        [Column("FeatureId")]
	    public string FeatureId { get; set; }
	      
        public virtual Feature Feature { get; set; }
        [Column("MenuButtonType")]
	    public string MenuButtonType { get; set; }
        [Column("DropDownControl")]
	    public string DropDownControl { get; set; }
        [Column("Style")]
	    public string Style { get; set; }
        [Column("Width")]
	    public int Width { get; set; }
        [Column("ControlPath")]
	    public string ControlPath { get; set; }
        [Column("HtmlComponentPath")]
	    public string HtmlComponentPath { get; set; }
        [Column("LabelTextCodeCode")]
	    public string LabelTextCodeCode { get; set; }
        [Column("FeatureUniqeCode")]
	    public string FeatureUniqeCode { get; set; }
    }
}
	 