//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Amital
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> AmitalClassesGenerator.tt
//---   
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using AmitalCloud.Infrastructure.Domain.Interfaces;
using AmitalCloud.Infrastructure.Model.EntityClasses ;

namespace AmitalCloud.Infrastructure.Application
{
   public class EntityLastActivityTypeDetails : EntityLastActivityType, ICloseTable<EntityLastActivityType, EntityLastActivityTypeDetails>
   {
       public List<EntityLastActivityTypeDetails> GetAll()
       {
		    var all = new List<EntityLastActivityTypeDetails>(); 
            return all;
       }

	    public void MapPoco(EntityLastActivityType newPoco)
        {    
        }

		public string GetSearchFields(EntityLastActivityType rec)
        {   
           return string.Empty;
        }
   }
}

