//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> MetadataClassesGenerator.tt AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.Linq;
using AmitalCloud.Infrastructure.Data.Context;
using AmitalCloud.Infrastructure.Data.DBHelpers;
using AmitalCloud.Infrastructure.Data.Repositories;
using AmitalCloud.Infrastructure.Domain.EntityPMs;
using AmitalCloud.Infrastructure.Model.EntityClasses;
using AmitalCloud.Infrastructure.Model.Interfaces;
using AmitalCloud.Infrastructure.MUpdater.Data.AddClasses;
using AmitalCloud.Infrastructure.Application;


namespace AmitalCloud.Infrastructure.MUpdater.Data.DataUpdate.GeneratedUpdate.AutoCreated
{
   public class DocumentsFilingMetaDataValueUpdateClass
   {  		
		public const string HashString = "f44b40315d4b65571b422ac277bb2e89";
	    public void AddObjectTable(Dictionary<string, ObjectTable> objectTables, Dictionary<string, TextCode> textCodes,Repository<ObjectTable> ObjectTableRepository,Repository<TextCode> TextCodeRepository,int contextTenant=0)
        {                     
            
            AddObjectsAndObjectFields.AddObjectTable(new ObjectTablePM()
            {
			
	             				    ObjectTableName =  "DocumentsFilingMetaDataValue",
			      				    IsNew =  false,
			      				    DBTableName =  "DocumentsFilingMetaDataValues",
			      				    ObjectTableSingular =  "DocumentsFilingMetaDataValue",
			      				    ObjectTablePlural =  "DocumentsFilingMetaDataValues",
			      				    HasCustomFilter =  false,
			      				    HasCustomFields =  false,
			      				    AvailableInCustomization =  false,
			      				    SupportSubEntity =  false,
			      				    ApplyGenericCustomFields =  false,
			      				    AvailableInDocumentTypes =  false,
			      				    IsLock =  false,
			      				    HasHelper =  false,
			      				    HasShortTitle =  false,
			      				    HasFiltersMenu =  false,
			      				    IsEditable =  true,
			      				    IsNewWizard =  false,
			      				    KeyPropertyPath =  "Id",
			      				    AutoCompleteSearchWindow =  false,
			      				    IsClosed =  false,
			      				    CacheOnClient =  false,
			      				    EditableFromAutoCompleteWindow =  false,
			      				    HasCounter =  false,
			      				    EnableAddFromLOV =  false,
			      				    IsRestrictable =  false,
			      				    IsMain =  true,
			      				    IsAutoComplete =  false,
			      				    EnableEditFromLOV =  false,
			      				    SortingByObjectField =  "Id",
			      				    InActive =  false,
			      				    IsSaveButtonVisible =  true,
			      				    IsComposition =  false,
			      				    EnableSecurity =  false,
			      				    AllowCustomFields =  false,
			      				    HasDynamicHeader =  false,
			      				    ObjectTableTypeCode =  "MD",
			      				    MaxNumberOfCustomFields =  0,
			      				    DefaultText =  "DocumentsFilingMetaDataValue",
			      				    Code =  "42b5",
			      				    Name =  "DocumentsFilingMetaDataValue",
			      				    CloseTableCode =  " & quot;Code&quot;",
			      				    CloseTableName =  " & quot;Name&quot;",
			      				    GenerateDomainService =  false,
			      				    NoTS =  false,
			      				    HasMenuButtons =  false,
			      				    AllowedForComputingPartners =  false,
			      				    ShowFastSearch =  false,
			      				    CustomFieldsCount =  0,
			      				    DisableSearchBox =  false,
			      				    HasDocuments =  false,
			      				    IsLookUp =  false,
			      				    IsTabsHidden =  false,
			      				    HashString =  DocumentsFilingMetaDataValueUpdateClass.HashString,
			                    
            }, ObjectTableRepository, TextCodeRepository, objectTables, textCodes,contextTenant);
		}
	
	    public void AddObjectFields(Dictionary<string, ObjectField> objectFields, Dictionary<string, ObjectTable> objectTables, Dictionary<string, TextCode> textCodes,Repository<ObjectField> ObjectFieldsRepository,Repository<TextCode> TextCodeRepository, List<ObjectField> addedFields, List<TextCode> addedTextCodes,int contextTenant)
	    {
	         
			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "Id",
					  						ObjectTableName =  "DocumentsFilingMetaDataValue",
					  						FieldsDataType =  "Text",
					  						MinLength =  0,
					  						MaxLength =  15,
					  						IsRequired =  true,
					  						CopyToDW =  false,
					  						DisplayOnLookUp =  false,
					  						DisplayOnLookUpLocal =  false,
					  						CanFilter =  false,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  true,
					  						IsCustomFilter =  false,
					  						IsListFilter =  false,
					  						Operator =  " & quot;StartsWith&quot;",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						PMPropertyPath =  "Id",
					  						ListPropertyPath =  "Id",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						DependencyFilter3IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						Code =  "Id",
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						DisplayInDocumentReferences =  false,
					  						NumberOfDigits =  0,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						FullFieldLable =  "Id",
					  						DefaultText =  "Id",
					  						IsForeignKey =  false,
					  						IsMaxLength =  false,
					  						NoMetaDataField =  false,
					  						IsFixedLength =  false,
					  						EnableAutoFill =  false,
					  						IncludeInSearchField =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						DisplayInAutomationAsEnitity =  false,
					  						DisplayInRequiredFields =  false,
					  						HasTemplate =  false,
					  						IsCustom =  false,
					  						HelpTextCode =  "Id",
					  						EnableFullscreenTextBox =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "Tenant",
					  						ObjectTableName =  "DocumentsFilingMetaDataValue",
					  						FieldsDataType =  "Integer",
					  						MinLength =  0,
					  						MaxLength =  0,
					  						IsRequired =  true,
					  						CopyToDW =  false,
					  						DisplayOnLookUp =  false,
					  						DisplayOnLookUpLocal =  false,
					  						CanFilter =  false,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  true,
					  						IsCustomFilter =  false,
					  						IsListFilter =  false,
					  						Operator =  " & quot;StartsWith&quot;",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						PMPropertyPath =  "Tenant",
					  						ListPropertyPath =  "Tenant",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						DependencyFilter3IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						Code =  "Tenant",
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						DisplayInDocumentReferences =  false,
					  						NumberOfDigits =  0,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						FullFieldLable =  "Tenant",
					  						DefaultText =  "Tenant",
					  						IsForeignKey =  false,
					  						IsMaxLength =  false,
					  						NoMetaDataField =  false,
					  						IsFixedLength =  false,
					  						EnableAutoFill =  false,
					  						IncludeInSearchField =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						DisplayInAutomationAsEnitity =  false,
					  						DisplayInRequiredFields =  false,
					  						HasTemplate =  false,
					  						IsCustom =  false,
					  						HelpTextCode =  "Tenant",
					  						EnableFullscreenTextBox =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "DocumentsFilingId",
					  						ObjectTableName =  "DocumentsFilingMetaDataValue",
					  						FieldsDataType =  "Text",
					  						MinLength =  0,
					  						MaxLength =  40,
					  						IsRequired =  true,
					  						CopyToDW =  false,
					  						DisplayOnLookUp =  false,
					  						DisplayOnLookUpLocal =  false,
					  						CanFilter =  false,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  true,
					  						IsCustomFilter =  false,
					  						IsListFilter =  false,
					  						Operator =  " & quot;StartsWith&quot;",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						PMPropertyPath =  "DocumentsFilingId",
					  						ListPropertyPath =  "DocumentsFilingId",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						DependencyFilter3IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						Code =  "DocumentsFilingId",
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						DisplayInDocumentReferences =  false,
					  						NumberOfDigits =  0,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						FullFieldLable =  "DocumentsFilingId",
					  						DefaultText =  "DocumentsFilingId",
					  						IsForeignKey =  true,
					  						ForeignEntity =  "DocumentsFiling",
					  						NavigationPropertyName =  "DocumentsFiling",
					  						IsMaxLength =  false,
					  						NoMetaDataField =  false,
					  						IsFixedLength =  false,
					  						EnableAutoFill =  false,
					  						IncludeInSearchField =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						DisplayInAutomationAsEnitity =  false,
					  						DisplayInRequiredFields =  false,
					  						HasTemplate =  false,
					  						IsCustom =  false,
					  						HelpTextCode =  "DocumentsFilingId",
					  						EnableFullscreenTextBox =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "DocumentsMetaDataTypeId",
					  						ObjectTableName =  "DocumentsFilingMetaDataValue",
					  						FieldsDataType =  "Text",
					  						MinLength =  0,
					  						MaxLength =  15,
					  						IsRequired =  true,
					  						CopyToDW =  false,
					  						DisplayOnLookUp =  false,
					  						DisplayOnLookUpLocal =  false,
					  						CanFilter =  false,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  true,
					  						IsCustomFilter =  false,
					  						IsListFilter =  false,
					  						Operator =  " & quot;StartsWith&quot;",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						PMPropertyPath =  "DocumentsMetaDataTypeId",
					  						ListPropertyPath =  "DocumentsMetaDataTypeId",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						DependencyFilter3IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						Code =  "DocumentsMetaDataTypeId",
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						DisplayInDocumentReferences =  false,
					  						NumberOfDigits =  0,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						FullFieldLable =  "DocumentsMetaDataTypeId",
					  						DefaultText =  "DocumentsMetaDataTypeId",
					  						IsForeignKey =  true,
					  						ForeignEntity =  "DocumentsMetaDataType",
					  						NavigationPropertyName =  "DocumentsMetaDataType",
					  						IsMaxLength =  false,
					  						NoMetaDataField =  false,
					  						IsFixedLength =  false,
					  						EnableAutoFill =  false,
					  						IncludeInSearchField =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						DisplayInAutomationAsEnitity =  false,
					  						DisplayInRequiredFields =  false,
					  						HasTemplate =  false,
					  						IsCustom =  false,
					  						HelpTextCode =  "DocumentsMetaDataTypeId",
					  						EnableFullscreenTextBox =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "MetaDataValue",
					  						ObjectTableName =  "DocumentsFilingMetaDataValue",
					  						FieldsDataType =  "nText",
					  						MinLength =  0,
					  						MaxLength =  128,
					  						IsRequired =  true,
					  						CopyToDW =  false,
					  						DisplayOnLookUp =  false,
					  						DisplayOnLookUpLocal =  false,
					  						CanFilter =  false,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  true,
					  						IsCustomFilter =  false,
					  						IsListFilter =  false,
					  						Operator =  " & quot;StartsWith&quot;",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						PMPropertyPath =  "MetaDataValue",
					  						ListPropertyPath =  "MetaDataValue",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						DependencyFilter3IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						Code =  "MetaDataValue",
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						DisplayInDocumentReferences =  false,
					  						NumberOfDigits =  0,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						FullFieldLable =  "MetaDataValue",
					  						DefaultText =  "MetaDataValue",
					  						IsForeignKey =  false,
					  						IsMaxLength =  false,
					  						NoMetaDataField =  false,
					  						IsFixedLength =  false,
					  						EnableAutoFill =  false,
					  						IncludeInSearchField =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						DisplayInAutomationAsEnitity =  false,
					  						DisplayInRequiredFields =  false,
					  						HasTemplate =  false,
					  						IsCustom =  false,
					  						HelpTextCode =  "MetaDataValue",
					  						EnableFullscreenTextBox =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 
	    }

	    public void AddTableQueries(Dictionary<string, Query> tenantQueries,Dictionary<string, QueryColumn> tenantQueryColumns, Dictionary<string, ObjectTable> objectTables, Dictionary<string, TextCode> textCodes, Repository<QueryGroup> queryGroupRepository, Repository<Query> queriesRepository, Repository<QueryColumn> queryColumnsRepository,Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository, Dictionary<string, Feature> TenantFeatures,Repository<AdvancedQueryFilter> advancedQueryFiltersRepository,Dictionary<string, AdvancedQueryFilter> tenantAdvancedFilters,Dictionary<string, QueryGroup> tenantQueryGroups ,int contextTenant)
	    {    
	    }

	    public void AddTableScreens(Dictionary<string, Screen> tenantScreens,Dictionary<string, ScreenField> tenantScreenFields, Repository<Screen> screensRepository, Repository<ScreenField> screenFieldsRepository,IAmitalCloudContext ObjectContext,int contextTenant)
	    {   

		   ObjectTable DocumentsFilingMetaDataValueObjectTable = ObjectContext.ObjectTables.Where(d => d.Name == "DocumentsFilingMetaDataValue" && d.Tenant == 0).FirstOrDefault();
		   //List<ObjectField> DocumentsFilingMetaDataValueObjectFields = ObjectContext.ObjectFields.Where(d => d.ObjectTable.Name == "DocumentsFilingMetaDataValue").ToList();
		       
	      

	         Screen DocumentsFilingMetaDataValueDocumentsFilingMetaDataValueHeaderScreenScreen0 = AddScreensAndScreenFields.AddScreen(new ScreenPM() { Code = "DocumentsFilingMetaDataValue.HeaderScreen", Name = "DocumentsFilingMetaDataValueHeaderScreen", ObjectTableId = DocumentsFilingMetaDataValueObjectTable.Id, NumberOfColumns = 2, NumberOfRows = 1, IsReadOnly = true }, screensRepository, tenantScreens,contextTenant);
      	
		    DocumentsFilingMetaDataValueObjectTable.HeaderScreenId = DocumentsFilingMetaDataValueDocumentsFilingMetaDataValueHeaderScreenScreen0.Id;
		    DocumentsFilingMetaDataValueObjectTable.HeaderScreenCode = DocumentsFilingMetaDataValueDocumentsFilingMetaDataValueHeaderScreenScreen0.Code;

	   		  

	    }

	    public void AddTableTabs(Dictionary<string, ObjectTableTab> TenantObjectTableTabs, Dictionary<string, TextCode> textCodes,Repository<ObjectTableTab> objectTableTabsRepository,Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository,Dictionary<string, Feature> TenantFeatures ,IAmitalCloudContext ObjectContext,int contextTenant)
	    {      
	    } 
	
	    public void AddTableFeatures(Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository,Dictionary<string, Feature> TenantFeatures,Dictionary<string, TextCode> TextCodes,IAmitalCloudContext ObjectContext,int contextTenant)
	    {  
		   ObjectTable DocumentsFilingMetaDataValueObjectTable = ObjectContext.ObjectTables.Where(d => d.Name == "DocumentsFilingMetaDataValue" && d.Tenant == 0).FirstOrDefault(); 

		   Feature DocumentsFilingMetaDataValueFeatureNew = AddRolesAndFeaturesClass.AddFeature(new FeaturePM() { Code = "NEW", FeatureTypeCode = "NEW", IsBusinessUnitEnabled = false, ObjectTableId = DocumentsFilingMetaDataValueObjectTable.Id, Tenant = 0, NameTextCodeCode = "DocumentsFilingMetaDataValue.Features.New", NameTextCodeDefaultText = "New" }, FeaturesRepository, TextCodeRepository, TenantFeatures, TextCodes,DocumentsFilingMetaDataValueObjectTable,contextTenant);
		   Feature DocumentsFilingMetaDataValueFeatureRead = AddRolesAndFeaturesClass.AddFeature(new FeaturePM() { Code = "READ", FeatureTypeCode = "READ", IsBusinessUnitEnabled = false, ObjectTableId = DocumentsFilingMetaDataValueObjectTable.Id, Tenant = 0, NameTextCodeCode = "DocumentsFilingMetaDataValue.Features.Read", NameTextCodeDefaultText = "Read" }, FeaturesRepository, TextCodeRepository, TenantFeatures, TextCodes,DocumentsFilingMetaDataValueObjectTable,contextTenant);
		   Feature DocumentsFilingMetaDataValueFeatureUpdate = AddRolesAndFeaturesClass.AddFeature(new FeaturePM() { Code = "UPDATE", FeatureTypeCode = "UPDT", IsBusinessUnitEnabled = false, ObjectTableId = DocumentsFilingMetaDataValueObjectTable.Id, Tenant = 0, NameTextCodeCode = "DocumentsFilingMetaDataValue.Features.Edit", NameTextCodeDefaultText = "Edit" }, FeaturesRepository, TextCodeRepository, TenantFeatures, TextCodes,DocumentsFilingMetaDataValueObjectTable,contextTenant);
		   Feature DocumentsFilingMetaDataValueFeatureModule = AddRolesAndFeaturesClass.AddFeature(new FeaturePM() { Code = "Module", FeatureTypeCode = "MODL", IsBusinessUnitEnabled = false, ObjectTableId = DocumentsFilingMetaDataValueObjectTable.Id, Tenant = 0, NameTextCodeCode = "DocumentsFilingMetaDataValue.Features.PackageFeature", NameTextCodeDefaultText = "DocumentsFilingMetaDataValue Package Feature", Packagable = true }, FeaturesRepository, TextCodeRepository, TenantFeatures, TextCodes,DocumentsFilingMetaDataValueObjectTable,contextTenant);    
	    
		}

	    public void AddTableEventTypes(Dictionary<string, EventType> tenantEventTypes,Repository<EventType> EventTypeRepository,IAmitalCloudContext ObjectContext,List<EntityStatus> AllEntityStatuses,int contextTenant)
	    {   
			ObjectTable DocumentsFilingMetaDataValueObjectTable = ObjectContext.ObjectTables.Where(d => d.Name == "DocumentsFilingMetaDataValue" && d.Tenant == 0).FirstOrDefault(); 
            AddEventTypes.AddEventType(new EventTypePM()
            {
                Code =  "CREV",
                EnglishName =  "Created",
                LocalName =  "Created",
                IsManualEntry =  false,
                ShortView =  true,
                IsAgentView =  false,
                IsCustomerView =  false,
                IsSharedLogisticsEnabled =  false,
                AllowedInAutomation =  false,
                ManualActivatedFollowUp =  false,
                IsFollowUp =  false,
                ObjectTableId = DocumentsFilingMetaDataValueObjectTable.Id,
				 
            }, EventTypeRepository, tenantEventTypes,contextTenant);


            AddEventTypes.AddEventType(new EventTypePM()
            {
                Code =  "UPEV",
                EnglishName =  "Updated",
                LocalName =  "Updated",
                IsManualEntry =  false,
                ShortView =  false,
                IsAgentView =  false,
                IsCustomerView =  false,
                IsSharedLogisticsEnabled =  false,
                AllowedInAutomation =  false,
                ManualActivatedFollowUp =  false,
                IsFollowUp =  false,
                ObjectTableId = DocumentsFilingMetaDataValueObjectTable.Id,
				 
            }, EventTypeRepository, tenantEventTypes,contextTenant);


	    }
	
	    public void AddTableMenuButtons(Dictionary<string, MenuButton> tenantMenuButtons,Dictionary<string, MenuButtonGroup> tenantMenuButtonGroups, Dictionary<string, TextCode> textCodes,Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository, Repository<MenuButton> menuButtonRepository,Dictionary<string, Feature> TenantFeatures,Repository<MenuButtonGroup> menuButtonGroupRepository ,IAmitalCloudContext ObjectContext,int contextTenant)
	    {  
	    }

	    public void AddTableTextCodes(Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository,Dictionary<string, Feature> TenantFeatures,Dictionary<string, TextCode> TextCodes,IAmitalCloudContext ObjectContext,int contextTenant)
	    {     
	    
}

    

   }
    
}
	 