//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> ShipmentClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using AmitalCloud.Infrastructure.Data.Context;
using AmitalCloud.Infrastructure.Data.DBHelpers;
using AmitalCloud.Infrastructure.Data.Helpers;
using AmitalCloud.Infrastructure.Data.Repositories;
using AmitalCloud.Infrastructure.Domain.EntityPMs;
using AmitalCloud.Infrastructure.Model.EntityClasses;
using AmitalCloud.Infrastructure.Model.Interfaces;
using AmitalCloud.Infrastructure.MUpdater.Data.AddClasses;
using AmitalCloud.Shipment.Application;
using AmitalCloud.Infrastructure.MUpdater.Data.Helpers;
using AmitalCloud.Infrastructure.MUpdater.Data.DataUpdate.GeneratedUpdate.ShipmentsModel.Master;
using AmitalCloud.Infrastructure.MUpdater.Data.DataUpdate.GeneratedUpdate.ShipmentsModel;

namespace AmitalCloud.Infrastructure.MUpdater.Data.DataUpdate
{
   public class MasterModelUpdateClass
   {
        public Dictionary<string, ObjectTable> ObjectTables { get; set; }
	    public Dictionary<string, TextCode> TextCodes { get; set; }
	    public Repository<ObjectTable> ObjectTableRepository { get; set; }
	    public Repository<TextCode> TextCodeRepository { get; set; } 
		public Dictionary<string, ObjectField> ObjectFields { get; set; }
	    public Repository<ObjectField> ObjectFieldsRepository { get; set; }
		public IAmitalCloudContext ObjectContext { get; set; }
		public Dictionary<string, Query> Queries {get; set; }
		public Dictionary<string, QueryColumn> QueryColumns {get; set; }
		public Repository<Query> queriesRepository { get; set; } 
		public Repository<QueryColumn> queryColumnsRepository { get; set; } 
		public Repository<Feature> FeaturesRepository { get; set; }
		public Dictionary<string, Feature> TenantFeatures { get; set; }
		public Repository<QueryGroup> queryGroupRepository{ get; set; }
		public Repository<AdvancedQueryFilter> advancedQueryFiltersRepository {get;set;}
		public Dictionary<string, AdvancedQueryFilter> tenantAdvancedFilters {get; set; }
		public Repository<Screen> screensRepository {get;set;}
		public Dictionary<string, Screen> tenantScreens {get; set; }
		public Repository<ScreenField> screenFieldsRepository {get;set;}
		public Dictionary<string, ScreenField> tenantScreenFields {get; set; }
		public Dictionary<string, ObjectTableTab> TenantObjectTableTabs {get; set; }
		public Repository<ObjectTableTab> objectTableTabsRepository {get;set;}
	    public Dictionary<string, EventType> tenantEventTypes {get;set;}
		public Repository<EventType> EventTypeRepository {get;set;}
		public Repository<MenuButton> menuButtonRepository {get;set;}
		public Repository<MenuButtonGroup> menuButtonGroupRepository {get;set;} 
		public Dictionary<string, MenuButton> tenantMenuButtons {get;set;}
		public Dictionary<string, MenuButtonGroup> tenantMenuButtonGroups {get;set;}
		public Repository<EntityStatus> EntityStatusRepository { get; set; }
		public  List<EntityStatus>  AllEntityStatuses { get; set; }
		Dictionary<string, QueryGroup> tenantQueryGroups {get; set; }
		 
	   	MasterUpdateClass  MasterUpdateClass = new MasterUpdateClass();
	
		public void LoadObjectsTenantZero(IAmitalCloudContext context, int contextTenant=0)
        {
            ObjectContext = context;
            TextCodeRepository = new Repository<TextCode>(ObjectContext);
            ObjectTableRepository = new Repository<ObjectTable>(ObjectContext);
            ObjectFieldsRepository = new Repository<ObjectField>(ObjectContext);
			queriesRepository = new Repository<Query>(ObjectContext);
			queryColumnsRepository = new Repository<QueryColumn>(ObjectContext);
            queryGroupRepository = new Repository<QueryGroup>(ObjectContext);
			advancedQueryFiltersRepository = new Repository<AdvancedQueryFilter>(ObjectContext);
			screensRepository = new Repository<Screen>(ObjectContext);
			screenFieldsRepository = new Repository<ScreenField>(ObjectContext);
			objectTableTabsRepository = new Repository<ObjectTableTab>(ObjectContext);
			EventTypeRepository = new Repository<EventType>(ObjectContext);
			menuButtonRepository = new Repository<MenuButton>(ObjectContext);
			menuButtonGroupRepository = new Repository<MenuButtonGroup>(ObjectContext);
			FeaturesRepository = new Repository<Feature>(ObjectContext);
			EntityStatusRepository = new Repository<EntityStatus>(ObjectContext);

            TextCodes = TextCodeRepository.GetAll(0).ToDictionary(d => d.Code + d.Tenant.ToString() + d.ObjectTableId, a => a, StringComparer.OrdinalIgnoreCase);
            ObjectTables = ObjectTableRepository.GetAll(0).ToDictionary(d => d.Name, a => a);
            ObjectFields = ObjectFieldsRepository.GetAll(0).ToDictionary(d => d.FieldName + d.ObjectTableId, a => a);
			Queries = queriesRepository.GetAll(0).ToDictionary(d => d.Code + d.ObjectTableId, a => a);
            QueryColumns = queryColumnsRepository.GetAll(0).ToDictionary(d => d.QueryCode + d.ObjectFieldCode, a => a);
			TenantFeatures = FeaturesRepository.GetAll(0).ToDictionary(d => d.Code + d.ObjectTableId, a => a);
			tenantAdvancedFilters = advancedQueryFiltersRepository.GetAll(0).ToDictionary(d => d.QueryCode + d.ObjectFieldCode, a => a);
			tenantScreens = screensRepository.GetAll(0).ToDictionary(d => d.Code + d.ObjectTableId, a => a);
			tenantScreenFields = screenFieldsRepository.GetAll(0).ToDictionary(d => d.ScreenCode + d.ObjectFieldCode);
			TenantObjectTableTabs = objectTableTabsRepository.GetAll(0).ToDictionary(d => d.Code, a => a);
			tenantEventTypes = EventTypeRepository.GetAll(0).ToDictionary(d => d.Code + d.ObjectTableId, a => a);
			tenantMenuButtons = menuButtonRepository.GetAll(0).ToDictionary(d => d.EventCode + d.MenuButtonGroupId, a => a);
			tenantMenuButtonGroups = menuButtonGroupRepository.GetAll(0).ToDictionary(d => d.Name, a => a);
			AllEntityStatuses = EntityStatusRepository.GetAll(0).ToList();


			CreateAllObjectTables(contextTenant);
		    this.ObjectContext.SaveChanges();
			
			CreateAllObjectFields(contextTenant);
		    this.ObjectContext.SaveChanges();

			CreateAllQueries(contextTenant);
		    this.ObjectContext.SaveChanges();

			CreateAllScreens(contextTenant);
		    this.ObjectContext.SaveChanges();

			CreateAllTabs(contextTenant);
		    this.ObjectContext.SaveChanges();

			CreateAllEventTypes(contextTenant);
		    this.ObjectContext.SaveChanges();

			CreateAllClosedTables(contextTenant);
		    this.ObjectContext.SaveChanges();

			CreateAllFeatures(contextTenant);
			CreateAdditionalTextCodes(contextTenant);
		    this.ObjectContext.SaveChanges();

			CreateAllMenuButtons(contextTenant);
		    this.ObjectContext.SaveChanges();

        }

		public void LoadObjectTablesMetadata(IAmitalCloudContext context, bool runPostDeleteProcedure,int contextTenant=0)
        {
		    ObjectContext = context;
            TextCodeRepository = new Repository<TextCode>(context);
            ObjectTableRepository = new Repository<ObjectTable>(context);
            ObjectFieldsRepository = new Repository<ObjectField>(context);
            queriesRepository = new Repository<Query>(context);
            queryColumnsRepository = new Repository<QueryColumn>(context);
            queryGroupRepository = new Repository<QueryGroup>(context);
            advancedQueryFiltersRepository = new Repository<AdvancedQueryFilter>(context);
            screensRepository = new Repository<Screen>(context);
            screenFieldsRepository = new Repository<ScreenField>(context);
            objectTableTabsRepository = new Repository<ObjectTableTab>(context);
            EventTypeRepository = new Repository<EventType>(context);
            menuButtonRepository = new Repository<MenuButton>(context);
            menuButtonGroupRepository = new Repository<MenuButtonGroup>(context);
            FeaturesRepository = new Repository<Feature>(context);
            EntityStatusRepository = new Repository<EntityStatus>(context);


             ObjectTables = ObjectTableRepository.GetAll(0).ToDictionary(d => d.Name, a => a);
            ObjectTable generalTable = ObjectTables["General"];
            TextCodes = TextCodeRepository.GetAll(0).Where(t => t.ObjectTableId == generalTable.Id).ToDictionary(d => d.Code + d.Tenant.ToString() + d.ObjectTableId, a => a, StringComparer.OrdinalIgnoreCase);
			TenantFeatures = FeaturesRepository.GetAll(0).Where(t => t.ObjectTableId == generalTable.Id).ToDictionary(d => d.Code + d.ObjectTableId, a => a);
			ObjectFields = new Dictionary<string, ObjectField>();
			Queries = new Dictionary<string, Query>();
			QueryColumns = new Dictionary<string, QueryColumn>();
			tenantAdvancedFilters = new Dictionary<string, AdvancedQueryFilter>();
			tenantScreens = new Dictionary<string, Screen>();
			tenantScreenFields = new Dictionary<string, ScreenField>();
			TenantObjectTableTabs = new Dictionary<string, ObjectTableTab>();
			tenantEventTypes = EventTypeRepository.GetAll(0).ToDictionary(d => d.Code + d.ObjectTableId, a => a);
			tenantMenuButtons = new Dictionary<string, MenuButton>();
			tenantMenuButtonGroups = menuButtonGroupRepository.GetAll(0).ToDictionary(d => d.Name, a => a);
			AllEntityStatuses = EntityStatusRepository.GetAll(0).ToList();
			tenantQueryGroups = queryGroupRepository.GetQueryable().ToDictionary(d => d.Code, a => a);	


			 MetadataUpdateUtility.RunPreDeleteProcedure(contextTenant);

			 CreateAllObjectTablesMetadata(contextTenant);
			 
 
			 this.ObjectContext.SaveChanges();
			 if(runPostDeleteProcedure)
			 {
				MetadataUpdateUtility.RunPostDeleteProcedure(contextTenant);
			 }
			
        }

		private static Dictionary<string,string> TablesHashStrings { get; set; }		 
	    public static Dictionary<string, string> GetAllTablesHashStrings()
        {
			if (TablesHashStrings != null)
				return TablesHashStrings;

			TablesHashStrings = new Dictionary<string, string>();
 			TablesHashStrings.Add("Master",  MasterUpdateClass.HashString);
			return TablesHashStrings;
        }
        public void CreateAllObjectTablesMetadata(int contextTenant)
        {
   
			if(MetadataUpdateUtility.IsChangedMetadataTable("Master", ObjectTables, MasterUpdateClass.HashString))
			{
				using (TransactionScope scope = TransactionFactory.GetNewTransaction())
				{				
					MetadataUpdateUtility.DeleteAllTableMetadata("Master",contextTenant);
					MasterUpdateClass.AddObjectTable(ObjectTables, TextCodes, ObjectTableRepository,TextCodeRepository,contextTenant);
					this.ObjectContext.SaveChanges();
					List<ObjectField> addedFields = new List<ObjectField>();
					List<TextCode> addedTextCodes = new List<TextCode>();
					MasterUpdateClass.AddObjectFields(ObjectFields, ObjectTables, TextCodes, ObjectFieldsRepository, TextCodeRepository, addedFields, addedTextCodes,contextTenant);
					SqlBulkInsert.BulkInsert("TextCodes", addedTextCodes,contextTenant);
					SqlBulkInsert.BulkInsert("ObjectFields", addedFields,contextTenant);					
					
					MasterUpdateClass.AddTableQueries(Queries, QueryColumns, ObjectTables, TextCodes, queryGroupRepository, queriesRepository, queryColumnsRepository, TextCodeRepository, FeaturesRepository, TenantFeatures, advancedQueryFiltersRepository, tenantAdvancedFilters,tenantQueryGroups,contextTenant);
					MasterUpdateClass.AddTableScreens(tenantScreens, tenantScreenFields, screensRepository, screenFieldsRepository, ObjectContext,contextTenant);
					MasterUpdateClass.AddTableTabs(TenantObjectTableTabs, TextCodes, objectTableTabsRepository, TextCodeRepository, FeaturesRepository, TenantFeatures, ObjectContext,contextTenant);
					MasterUpdateClass.AddTableEventTypes(tenantEventTypes, EventTypeRepository, ObjectContext, AllEntityStatuses,contextTenant);
					MasterUpdateClass.AddTableFeatures(TextCodeRepository, FeaturesRepository, TenantFeatures, TextCodes, ObjectContext,contextTenant);
					MasterUpdateClass.AddTableTextCodes(TextCodeRepository, FeaturesRepository, TenantFeatures, TextCodes, ObjectContext,contextTenant);
					MasterUpdateClass.AddTableMenuButtons(tenantMenuButtons, tenantMenuButtonGroups, TextCodes, TextCodeRepository, FeaturesRepository, menuButtonRepository, TenantFeatures, menuButtonGroupRepository, ObjectContext,contextTenant);
					this.ObjectContext.SaveChanges();
					scope.Complete();
				}
			}

        }
   

        public void CreateAllObjectTables(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddObjectTable(ObjectTables, TextCodes, ObjectTableRepository,TextCodeRepository,contextTenant);
	
        }
   

        public void CreateAllObjectFields(int contextTenant)
        {
   
	   	   //MasterUpdateClass.AddObjectFields(ObjectFields, ObjectTables, TextCodes, ObjectFieldsRepository,TextCodeRepository,contextTenant);
	
        }

		public void CreateAllQueries(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddTableQueries(Queries,QueryColumns, ObjectTables, TextCodes,queryGroupRepository,queriesRepository,queryColumnsRepository,TextCodeRepository,FeaturesRepository,TenantFeatures,advancedQueryFiltersRepository,tenantAdvancedFilters,tenantQueryGroups,contextTenant);
	
        }

		public void CreateAllScreens(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddTableScreens(tenantScreens,tenantScreenFields,screensRepository,screenFieldsRepository,ObjectContext,contextTenant);
	
        }

		public void CreateAllTabs(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddTableTabs(TenantObjectTableTabs,TextCodes,objectTableTabsRepository,TextCodeRepository,FeaturesRepository,TenantFeatures,ObjectContext,contextTenant);
	
        }

		public void CreateAllEventTypes(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddTableEventTypes(tenantEventTypes,EventTypeRepository,ObjectContext,AllEntityStatuses,contextTenant);
	
        }

		public void CreateAllFeatures(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddTableFeatures(TextCodeRepository,FeaturesRepository,TenantFeatures,TextCodes,ObjectContext,contextTenant);
	
        }
		public void CreateAdditionalTextCodes(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddTableTextCodes(TextCodeRepository,FeaturesRepository,TenantFeatures,TextCodes,ObjectContext,contextTenant);
	
        }
		public void CreateAllMenuButtons(int contextTenant)
        {
   
	   	   MasterUpdateClass.AddTableMenuButtons(tenantMenuButtons,tenantMenuButtonGroups,TextCodes,TextCodeRepository,FeaturesRepository,menuButtonRepository,TenantFeatures,menuButtonGroupRepository ,ObjectContext,contextTenant);
	
        }

		public void CreateAllClosedTables(int contextTenant)
        {
   
	   
        }
 	 
	 

   }

}
