//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a logitude.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> MetadataClassesGenerator.tt AmitalClassesGenerator.tt
//---
using System;
using System.Collections.Generic;
using System.Linq;
using AmitalCloud.Infrastructure.Data.Context;
using AmitalCloud.Infrastructure.Data.DBHelpers;
using AmitalCloud.Infrastructure.Data.Repositories;
using AmitalCloud.Infrastructure.Domain.EntityPMs;
using AmitalCloud.Infrastructure.Model.EntityClasses;
using AmitalCloud.Infrastructure.Model.Interfaces;
using AmitalCloud.Infrastructure.MUpdater.Data.AddClasses;
using AmitalCloud.Infrastructure.Application;


namespace AmitalCloud.Infrastructure.MUpdater.Data.DataUpdate.GeneratedUpdate
{
   public class CustomerSalesNoteUpdateClass
   {  		
		public const string HashString = "e3d49065ac770b29e15b4c4f4a682373";
	    public void AddObjectTable(Dictionary<string, ObjectTable> objectTables, Dictionary<string, TextCode> textCodes,Repository<ObjectTable> ObjectTableRepository,Repository<TextCode> TextCodeRepository,int contextTenant=0)
        {                     
            
            AddObjectsAndObjectFields.AddObjectTable(new ObjectTablePM()
            {
			
	             				    IsComposition =  true,
			      				    ObjectTableName =  "CustomerSalesNote",
			      				    DBTableName =  "CustomerSalesNote",
			      				    ObjectTableSingular =  "Customer Sales Note",
			      				    ObjectTablePlural =  "Customer Sales Notes",
			      				    DefaultText =  "Customer Sales Note",
			      				    Name =  "CustomerSalesNote",
			      				    IsNewWizard =  false,
			      				    KeyPropertyPath =  "Id",
			      				    AutoCompleteSearchWindow =  false,
			      				    IsClosed =  false,
			      				    CacheOnClient =  false,
			      				    EditableFromAutoCompleteWindow =  false,
			      				    HasCounter =  false,
			      				    EnableEditFromLOV =  false,
			      				    EnableAddFromLOV =  false,
			      				    IsRestrictable =  false,
			      				    IsMain =  false,
			      				    IsAutoComplete =  false,
			      				    CustomFieldsCount =  0,
			      				    HasCustomFields =  false,
			      				    InActive =  false,
			      				    SearchFields =  "CustomerSalesNote,CustomerSalesNotes,,Id,",
			      				    IsSaveButtonVisible =  true,
			      				    EnableSecurity =  true,
			      				    ObjectTableTypeCode =  "BR",
			      				    MaxNumberOfCustomFields =  0,
			      				    AllowCustomFields =  false,
			      				    HasDynamicHeader =  false,
			      				    HasDocuments =  false,
			      				    IsLookUp =  false,
			      				    IsEditable =  true,
			      				    HashString =  CustomerSalesNoteUpdateClass.HashString,
			                    
            }, ObjectTableRepository, TextCodeRepository, objectTables, textCodes,contextTenant);
		}
	
	    public void AddObjectFields(Dictionary<string, ObjectField> objectFields, Dictionary<string, ObjectTable> objectTables, Dictionary<string, TextCode> textCodes,Repository<ObjectField> ObjectFieldsRepository,Repository<TextCode> TextCodeRepository, List<ObjectField> addedFields, List<TextCode> addedTextCodes,int contextTenant)
	    {
	         
			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "Id",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "Text",
					  						PMPropertyPath =  "Id",
					  						ListPropertyPath =  "Id",
					  						FullFieldLable =  "Id",
					  						DefaultText =  "Id",
					  						FullLocalDefaultText =  "Id",
					  						ListFieldLable =  "IdListLable",
					  						ListLableDefaultText =  "Id",
					  						ListLocalDefaultText =  "Id",
					  						IsRequired =  false,
					  						DisplayInList =  false,
					  						NoMetaDataField =  true,
					  						MaxLength =  15,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "Tenant",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "Integer",
					  						PMPropertyPath =  "Tenant",
					  						ListPropertyPath =  "Tenant",
					  						FullFieldLable =  "Tenant",
					  						DefaultText =  "Tenant",
					  						FullLocalDefaultText =  "Tenant",
					  						ListFieldLable =  "TenantListLable",
					  						ListLableDefaultText =  "Tenant",
					  						ListLocalDefaultText =  "Tenant",
					  						IsRequired =  false,
					  						DisplayInList =  false,
					  						NoMetaDataField =  true,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "CustomerId",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "LookUp",
					  						LookUpTableName =  "Customer",
					  						DataTypeCode =  "LookUp",
					  						MaxLength =  15,
					  						IsCustom =  false,
					  						MinLength =  0,
					  						DisplayOnLookUp =  false,
					  						CanFilter =  true,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  false,
					  						IsCustomFilter =  false,
					  						Operator =  "Equals",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						PMPropertyPath =  "CustomerId",
					  						ListPropertyPath =  "CustomerId",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						NumberOfDigits =  0,
					  						IsMaxLength =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						AllowedInAirlineMessaging =  false,
					  						FullFieldLable =  "CustomerId",
					  						DefaultText =  "Customer",
					  						HelpTextCode =  "CustomerId",
					  						Code =  "CustomerId",
					  						DependencyFilter3IsList =  false,
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInDocumentReferences =  false,
					  						CopyToDW =  false,
					  						HasTemplate =  false,
					  						IsRequired =  false,
					  						NoMetaDataField =  false,
					  						IsForeignKey =  true,
					  						ForeignEntity =  "Card",
					  						NavigationPropertyName =  "Customer",
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "CreatedByUserId",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "LookUp",
					  						LookUpTableName =  "User",
					  						DataTypeCode =  "LookUp",
					  						MaxLength =  15,
					  						IsCustom =  false,
					  						MinLength =  0,
					  						DisplayOnLookUp =  false,
					  						CanFilter =  true,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  false,
					  						IsCustomFilter =  false,
					  						Operator =  "Equals",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						PMPropertyPath =  "CreatedByUserId",
					  						ListPropertyPath =  "CreatedByUserId",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						NumberOfDigits =  0,
					  						IsMaxLength =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						AllowedInAirlineMessaging =  false,
					  						FullFieldLable =  "CreatedByUserId",
					  						DefaultText =  "Created By",
					  						HelpTextCode =  "CreatedByUserId",
					  						Code =  "CreatedByUserId",
					  						DependencyFilter3IsList =  false,
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInDocumentReferences =  false,
					  						CopyToDW =  false,
					  						HasTemplate =  false,
					  						IsRequired =  false,
					  						NoMetaDataField =  false,
					  						IsForeignKey =  true,
					  						ForeignEntity =  "User",
					  						NavigationPropertyName =  "CreatedByUser",
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "UpdatedByUserId",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "LookUp",
					  						LookUpTableName =  "User",
					  						DataTypeCode =  "LookUp",
					  						MaxLength =  15,
					  						IsCustom =  false,
					  						MinLength =  0,
					  						DisplayOnLookUp =  false,
					  						CanFilter =  true,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  false,
					  						IsCustomFilter =  false,
					  						Operator =  "Equals",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						PMPropertyPath =  "UpdatedByUserId",
					  						ListPropertyPath =  "UpdatedByUserId",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						NumberOfDigits =  0,
					  						IsMaxLength =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						AllowedInAirlineMessaging =  false,
					  						FullFieldLable =  "UpdatedByUserId",
					  						DefaultText =  "Updated By",
					  						HelpTextCode =  "UpdatedByUserId",
					  						Code =  "UpdatedByUserId",
					  						DependencyFilter3IsList =  false,
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInDocumentReferences =  false,
					  						CopyToDW =  false,
					  						HasTemplate =  false,
					  						IsRequired =  false,
					  						NoMetaDataField =  false,
					  						IsForeignKey =  true,
					  						ForeignEntity =  "User",
					  						NavigationPropertyName =  "UpdatedByUser",
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "CreateDate",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "DateTime",
					  						DataTypeCode =  "DateTime",
					  						MaxLength =  0,
					  						IsCustom =  false,
					  						MinLength =  0,
					  						DisplayOnLookUp =  false,
					  						CanFilter =  true,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  false,
					  						IsCustomFilter =  false,
					  						Operator =  "Equals",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						PMPropertyPath =  "CreateDate",
					  						ListPropertyPath =  "CreateDate",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						NumberOfDigits =  0,
					  						IsMaxLength =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						AllowedInAirlineMessaging =  false,
					  						FullFieldLable =  "CreateDate",
					  						DefaultText =  "Create Date",
					  						HelpTextCode =  "CreateDate",
					  						Code =  "CreateDate",
					  						DependencyFilter3IsList =  false,
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInDocumentReferences =  false,
					  						CopyToDW =  false,
					  						HasTemplate =  false,
					  						IsRequired =  false,
					  						NoMetaDataField =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "UpdateDate",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "DateTime",
					  						DataTypeCode =  "DateTime",
					  						MaxLength =  0,
					  						IsCustom =  false,
					  						MinLength =  0,
					  						DisplayOnLookUp =  false,
					  						CanFilter =  true,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  false,
					  						IsCustomFilter =  false,
					  						Operator =  "Equals",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						PMPropertyPath =  "UpdateDate",
					  						ListPropertyPath =  "UpdateDate",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						NumberOfDigits =  0,
					  						IsMaxLength =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						AllowedInAirlineMessaging =  false,
					  						FullFieldLable =  "UpdateDate",
					  						DefaultText =  "Update Date",
					  						HelpTextCode =  "UpdateDate",
					  						Code =  "UpdateDate",
					  						DependencyFilter3IsList =  false,
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInDocumentReferences =  false,
					  						CopyToDW =  false,
					  						HasTemplate =  false,
					  						IsRequired =  false,
					  						NoMetaDataField =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldName =  "Notes",
					  						ObjectTableName =  "CustomerSalesNote",
					  						FieldsDataType =  "nText",
					  						DataTypeCode =  "nText",
					  						MaxLength =  2000,
					  						IsCustom =  false,
					  						MinLength =  0,
					  						DisplayOnLookUp =  false,
					  						CanFilter =  false,
					  						DisplayOnly =  false,
					  						SystemRequired =  false,
					  						SystemMaxLength =  0,
					  						DisplayInList =  false,
					  						IsCustomFilter =  false,
					  						Operator =  "StartsWith",
					  						MultiLine =  false,
					  						IsTimeFrameFilter =  false,
					  						DisplayInSearchWindowList =  false,
					  						DisplayInSearchWindowFilters =  false,
					  						PMPropertyPath =  "Notes",
					  						ListPropertyPath =  "Notes",
					  						DisplayInLookUpIndex =  0,
					  						AutomaticField =  false,
					  						UniqueField =  false,
					  						DisplayInSearchWindowListIndex =  0,
					  						DisplayInSearchWindowFiltersIndex =  0,
					  						IsMulti =  false,
					  						DependencyFilter1IsList =  false,
					  						DependencyFilter2IsList =  false,
					  						IsRestrictable =  false,
					  						DisplayInEntityVariables =  true,
					  						DigitsAfterPoint =  0,
					  						InActive =  false,
					  						DisplayLongName =  false,
					  						NumberOfDigits =  0,
					  						IsMaxLength =  false,
					  						AllowedinAutomationConditions =  false,
					  						AutomationEmailRecipient =  false,
					  						CanAutomateSetValue =  false,
					  						AllowedInAirlineMessaging =  false,
					  						FullFieldLable =  "Notes",
					  						DefaultText =  "Notes",
					  						HelpTextCode =  "Notes",
					  						Code =  "Notes",
					  						DependencyFilter3IsList =  false,
					  						AllowedInCustomerFieldsSettings =  false,
					  						DisplayInDocumentReferences =  false,
					  						CopyToDW =  false,
					  						HasTemplate =  false,
					  						IsRequired =  false,
					  						NoMetaDataField =  false,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldsDataType =  "Text",
					  						FieldName =  "CreatedByUserName",
					  						PMPropertyPath =  "CreatedByUserName",
					  						ListPropertyPath =  "CreatedByUserName",
					  						FullFieldLable =  "CreatedByUserName",
					  						DefaultText =  "CreatedByUserName",
					  						FullLocalDefaultText =  "CreatedByUserName",
					  						ListFieldLable =  "CreatedByUserNameListLable",
					  						ListLableDefaultText =  "CreatedByUserName",
					  						ListLocalDefaultText =  "CreatedByUserName",
					  						ObjectTableName =  "CustomerSalesNote",
					  						NoMetaDataField =  true,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldsDataType =  "Text",
					  						FieldName =  "UpdatedByUserName",
					  						PMPropertyPath =  "UpdatedByUserName",
					  						ListPropertyPath =  "UpdatedByUserName",
					  						FullFieldLable =  "UpdatedByUserName",
					  						DefaultText =  "UpdatedByUserName",
					  						FullLocalDefaultText =  "UpdatedByUserName",
					  						ListFieldLable =  "UpdatedByUserNameListLable",
					  						ListLableDefaultText =  "UpdatedByUserName",
					  						ListLocalDefaultText =  "UpdatedByUserName",
					  						ObjectTableName =  "CustomerSalesNote",
					  						NoMetaDataField =  true,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldsDataType =  "Text",
					  						FieldName =  "ChangeSetOp",
					  						PMPropertyPath =  "ChangeSetOp",
					  						ListPropertyPath =  "ChangeSetOp",
					  						FullFieldLable =  "ChangeSetOp",
					  						DefaultText =  "ChangeSetOp",
					  						FullLocalDefaultText =  "ChangeSetOp",
					  						ListFieldLable =  "ChangeOpListLable",
					  						ListLableDefaultText =  "ChangeSetOp",
					  						ListLocalDefaultText =  "ChangeSetOp",
					  						ObjectTableName =  "CustomerSalesNote",
					  						NoMetaDataField =  true,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldsDataType =  "Text",
					  						FieldName =  "EventLabel",
					  						PMPropertyPath =  "EventLabel",
					  						ListPropertyPath =  "EventLabel",
					  						FullFieldLable =  "EventLabel",
					  						DefaultText =  "EventLabel",
					  						FullLocalDefaultText =  "EventLabel",
					  						ListFieldLable =  "EventLabelListLable",
					  						ListLableDefaultText =  "EventLabel",
					  						ListLocalDefaultText =  "EventLabel",
					  						ObjectTableName =  "CustomerSalesNote",
					  						NoMetaDataField =  true,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 

			   AddObjectsAndObjectFields.AddObjectField(new ObjectFieldPM() 
			   {
					 
					 						FieldsDataType =  "Boolean",
					  						FieldName =  "PostToFollowers",
					  						PMPropertyPath =  "PostToFollowers",
					  						ListPropertyPath =  "PostToFollowers",
					  						FullFieldLable =  "PostToFollowers",
					  						DefaultText =  "PostToFollowers",
					  						FullLocalDefaultText =  "PostToFollowers",
					  						ListFieldLable =  "PostToFollowersListLable",
					  						ListLableDefaultText =  "PostToFollowers",
					  						ListLocalDefaultText =  "PostToFollowers",
					  						ObjectTableName =  "CustomerSalesNote",
					  						NoMetaDataField =  true,
					  		
			   },TextCodeRepository,ObjectFieldsRepository,objectFields,textCodes,objectTables,addedFields,addedTextCodes,contextTenant);
 
	    }

	    public void AddTableQueries(Dictionary<string, Query> tenantQueries,Dictionary<string, QueryColumn> tenantQueryColumns, Dictionary<string, ObjectTable> objectTables, Dictionary<string, TextCode> textCodes, Repository<QueryGroup> queryGroupRepository, Repository<Query> queriesRepository, Repository<QueryColumn> queryColumnsRepository,Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository, Dictionary<string, Feature> TenantFeatures,Repository<AdvancedQueryFilter> advancedQueryFiltersRepository,Dictionary<string, AdvancedQueryFilter> tenantAdvancedFilters,Dictionary<string, QueryGroup> tenantQueryGroups ,int contextTenant)
	    {    
	    }

	    public void AddTableScreens(Dictionary<string, Screen> tenantScreens,Dictionary<string, ScreenField> tenantScreenFields, Repository<Screen> screensRepository, Repository<ScreenField> screenFieldsRepository,IAmitalCloudContext ObjectContext,int contextTenant)
	    {    

	    }

	    public void AddTableTabs(Dictionary<string, ObjectTableTab> TenantObjectTableTabs, Dictionary<string, TextCode> textCodes,Repository<ObjectTableTab> objectTableTabsRepository,Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository,Dictionary<string, Feature> TenantFeatures ,IAmitalCloudContext ObjectContext,int contextTenant)
	    {      
	    } 
	
	    public void AddTableFeatures(Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository,Dictionary<string, Feature> TenantFeatures,Dictionary<string, TextCode> TextCodes,IAmitalCloudContext ObjectContext,int contextTenant)
	    {     
	    
		}

	    public void AddTableEventTypes(Dictionary<string, EventType> tenantEventTypes,Repository<EventType> EventTypeRepository,IAmitalCloudContext ObjectContext,List<EntityStatus> AllEntityStatuses,int contextTenant)
	    {   
			ObjectTable CustomerSalesNoteObjectTable = ObjectContext.ObjectTables.Where(d => d.Name == "CustomerSalesNote" && d.Tenant == 0).FirstOrDefault(); 
	    }
	
	    public void AddTableMenuButtons(Dictionary<string, MenuButton> tenantMenuButtons,Dictionary<string, MenuButtonGroup> tenantMenuButtonGroups, Dictionary<string, TextCode> textCodes,Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository, Repository<MenuButton> menuButtonRepository,Dictionary<string, Feature> TenantFeatures,Repository<MenuButtonGroup> menuButtonGroupRepository ,IAmitalCloudContext ObjectContext,int contextTenant)
	    {  
	    }

	    public void AddTableTextCodes(Repository<TextCode> TextCodeRepository,Repository<Feature> FeaturesRepository,Dictionary<string, Feature> TenantFeatures,Dictionary<string, TextCode> TextCodes,IAmitalCloudContext ObjectContext,int contextTenant)
	    {     
	    
}

    

   }
    
}
	 